services:
  web:
    image: kubedevio/rotten-potatoes:v1
    ports:
      - "8080:5000"
    networks:
      - live_prometheus
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: "admin"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSWORD: "mongopwd"
      command: >
        gunicorn --timeout 90 --workers 4 app:app


  mongodb:
    image: mongo:7.0
    volumes:
      - db_mongo:/data/db
    networks:
      - live_prometheus
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - live_prometheus
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - live_prometheus

volumes:
  db_mongo:

networks:
  live_prometheus:
    driver: bridge
